name: Pelican site CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Pelican build
      run: make publish

    - uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.

    # - uses: nelsonjchen/gh-pages-pelican-action@0.1.5
    #   env:
    #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
