name: Pelican site CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout submodules
      run: git checkout
    # - uses: actions/checkout@v2
    # - name: Checkout
    #   uses: textbook/git-checkout-submodule-action@master
    # - name: Checkout submodules
    #   uses: textbook/git-checkout-submodule-action@master

    - name: Checkout submodules
      run: git submodule update --init --recursive

    # - name: Install requirements
    #   run: pip install -r requirements.txt

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        if [ -f requirements.txt ]; then python3 -m pip install -r requirements.txt; fi

    - name: Pelican build
      run: make publish

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master # The branch the action should deploy to.
        FOLDER: public # The folder the action should deploy.

    # - uses: nelsonjchen/gh-pages-pelican-action@0.1.5
    #   env:
    #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
